# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_msg_config -id {Synth 8-256} -limit 10000
set_msg_config -id {Synth 8-638} -limit 10000
create_project -in_memory -part xc7a75tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir /home/wajid/CA_Lab/UART/Riscv_3stage_piplined/cep2/cep2.cache/wt [current_project]
set_property parent.project_path /home/wajid/CA_Lab/UART/Riscv_3stage_piplined/cep2/cep2.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo /home/wajid/CA_Lab/UART/Riscv_3stage_piplined/cep2/cep2.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog /home/wajid/CA_Lab/UART/Riscv_3stage_piplined/design/DEFS/DEFS.svh
set_property file_type "Verilog Header" [get_files /home/wajid/CA_Lab/UART/Riscv_3stage_piplined/design/DEFS/DEFS.svh]
read_mem {
  /home/wajid/CA_Lab/UART/Riscv_3stage_piplined/data.mem
  /home/wajid/CA_Lab/UART/Riscv_3stage_piplined/inst.mem
}
read_verilog -library xil_defaultlib -sv {
  /home/wajid/CA_Lab/UART/Riscv_3stage_piplined/design/core/Adder4.sv
  /home/wajid/CA_Lab/UART/Riscv_3stage_piplined/design/core/LSU.sv
  /home/wajid/CA_Lab/UART/Riscv_3stage_piplined/design/core/PCCounter.sv
  /home/wajid/CA_Lab/UART/Riscv_3stage_piplined/design/core/alu.sv
  /home/wajid/CA_Lab/UART/Riscv_3stage_piplined/design/core/branch_cond.sv
  /home/wajid/CA_Lab/UART/Riscv_3stage_piplined/design/core/buff.sv
  /home/wajid/CA_Lab/UART/Riscv_3stage_piplined/design/core/buff_sync.sv
  /home/wajid/CA_Lab/UART/Riscv_3stage_piplined/design/core/controller.sv
  /home/wajid/CA_Lab/UART/Riscv_3stage_piplined/design/core/csr.sv
  /home/wajid/CA_Lab/UART/Riscv_3stage_piplined/design/core/ctrl_buff.sv
  /home/wajid/CA_Lab/UART/Riscv_3stage_piplined/design/core/dmem.sv
  /home/wajid/CA_Lab/UART/Riscv_3stage_piplined/design/core/forward_unit.sv
  /home/wajid/CA_Lab/UART/Riscv_3stage_piplined/design/core/imem.sv
  /home/wajid/CA_Lab/UART/Riscv_3stage_piplined/design/core/immediategeneration.sv
  /home/wajid/CA_Lab/UART/Riscv_3stage_piplined/design/core/mux2x1.sv
  /home/wajid/CA_Lab/UART/Riscv_3stage_piplined/design/core/mux_WB.sv
  /home/wajid/CA_Lab/UART/Riscv_3stage_piplined/design/core/register_file.sv
  /home/wajid/CA_Lab/UART/Riscv_3stage_piplined/design/core/main.sv
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
set_param ips.enableIPCacheLiteLoad 0
close [open __synthesis_is_running__ w]

synth_design -top main -part xc7a75tcsg324-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef main.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file main_utilization_synth.rpt -pb main_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
